### ISSUE TITLE
Split the section for phoebus services

### ISSUE THREAD

**Issue by shroffk** [kasemir/phoebus-doc#3]
Would it be too much trouble to split the Applications and the Services section in the documentation

all phoebus/app/.../doc are copied to Applications 
while
all phoebus/services/.../doc are copied to Services

**Comment by kasemir** [comment]
OK

**Comment by kasemir** [comment]
The 'Services' are now listed separately from 'Applications':

![doc](https://user-images.githubusercontent.com/1932421/49393430-391b8b80-f6ff-11e8-9b3e-66a150509e54.png)
